[project]
name = "mcpcrashcourse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-groq>=0.3.5",
    "mcp-use>=1.3.3",
    "mcp[cli]>=1.10.1",
    "nest-asyncio>=1.6.0",
]
